### ISSUE TITLE
Unexpected token 'null' on web

### ISSUE THREAD

**Issue by stevendz** [atn832/fake_firebase_security_rules#1]
<img width="937" alt="Screenshot 2023-02-21 at 14 27 24" src="https://user-images.githubusercontent.com/4571324/220357351-b2efa462-f397-452d-af65-fe7db9028179.png">

Because [fake_cloud_firestore](https://github.com/atn832/fake_cloud_firestore) is using this package, it will although not work on web atm.

This might be a naming problem for one of the files and might be happening while compiling dart code into JS code.

Reproduce:

- Create new flutter project (v. 3.7.3 stable)
- Add `fake_firebase_security_rules:` to dependencies
- Call `FakeFirebaseSecurityRules('');` somewhere, e.g. build method.

FYI: This error will only occure in debug mode, not in profile or release.

**Comment by atn832** [comment]
What are you trying to do? In theory, fake_firebase_security_rules is only used indirectly when using fake_cloud_firestore. Also it is used for running unit tests, so it should be added to dev dependencies instead of dependencies. Finally, you probably want to give it actual rules instead of empty string or the project will deny any request.

**Comment by atn832** [comment]
Oh I misread your message. You are experiencing this when using fake_cloud_firestore. Does it occur when passing a non-empty string, like actual rules?

**Comment by stevendz** [comment]
Thanks for the quick answer. 

I am using `FakeFirebaseFirestore()` and never inject `securityRules`.
It is although already a dev-dependency.

**Comment by atn832** [comment]
Your tip was spot on. I had a file called `null.dart`. After renaming it, it worked like a charm. I applied [the fix](https://github.com/atn832/cel-dart/commit/e957ae325f1798dab2ad3648aa61ed9ca0bfda9d) to cel, whgich fake_firebase_security_rules depends on. If you run `flutter pub upgrade`, it should transitively upgrade cel to the latest version, and it should fix it. Feel free to reopen the ticket if you still encounter the issue.
